### ISSUE TITLE
Meta: functions for measuring intragroup dynamics

### ISSUE THREAD

**Issue by robitalec** [ropensci/spatsoc#64]
Upcoming major release, with new functions for measuring intragroup dynamics (meta issue to track progress)

- [ ] Position within group, rank position within group
- [ ] Group bearing
- [ ] Time spent leading group
- [ ] Distance, bearing to leader
- [ ] Directional correlation delay
- [ ] Group centroid
- [ ] Distance, bearing to group centroid
- [ ] Polarization
- [ ] Directional alignment
- [ ] Interindividual direction
- [ ] Behavioural zones
- [ ] Fission fusion
